### ISSUE TITLE
Type ConsoleForElectron is not assignable

### ISSUE THREAD

**Issue by ghost** [jpoon/winston-console-for-electron#1]
When creating the logger as follows: 
```
import * as winston from 'winston'
import { ConsoleForElectron } from 'winston-console-for-electron'

const logger = winston.createLogger({
  defaultMeta: { service: `main:${process.pid}` },
  format: winston.format.json(),
  level: 'verbose',
  transports: [
    new winston.transports.File({ filename: 'error.log', level: 'error' }),
    new winston.transports.File({ filename: 'combined.log', level: 'verbose' }),
    new ConsoleForElectron(),
  ],
})
```
 
I get the following error for the line `new ConsoleForElectron()`:
```
(property) winston.LoggerOptions.transports?: TransportStream | TransportStream[]
Type '(FileTransportInstance | ConsoleForElectron)[]' is not assignable to type 'TransportStream | TransportStream[]'.
  Type '(FileTransportInstance | ConsoleForElectron)[]' is not assignable to type 'TransportStream[]'.
    Type 'FileTransportInstance | ConsoleForElectron' is not assignable to type 'TransportStream'.
      Type 'ConsoleForElectron' is missing the following properties from type 'TransportStream': writable, writableHighWaterMark, writableLength, _write, and 24 more.ts(2322)
index.d.ts(80, 5): The expected type comes from property 'transports' which is declared here on type 'LoggerOptions'
```

I saw that your library uses the v4.1.0 of winston-transport, so I tried an earlier version of winston library that uses v4.1.0 version of the winston-transport in the hopes that I could fix it maybe. The winston@3.0.0-rc6 was the one but still got the same error.

I am using the latest version of the winston library @3.2.1 with Electron (4.1.1) and TypeScript (3.4.3).

Any ideas on how to fixing it? Thank you.

**Comment by jpoon** [comment]
We're using it in vscodevim here: https://github.com/VSCodeVim/Vim/blob/e7dd01105ff038b1d27e53f8fa22058f3b5fc95f/src/util/logger.ts with winston 3.2.1: https://github.com/VSCodeVim/Vim/blob/master/package.json#L725

**Comment by ghost** [comment]
Changing the import statement in the library made it work for me:
from: `import * as TransportStream from 'winston-transport'`
to: `import TransportStream from 'winston-transport'`

**Comment by jpoon** [comment]
Interesting, they [winston] must have moved some stuff around. Feel free to submit a PR!

**Comment by AxelTerizaki** [comment]
I sadly am running into the same issue.

Using Winston 3.2.1 and Electron 8.

**Comment by jpoon** [comment]
0.0.7 published.
